# Generated by Django 5.2.1 on 2025-05-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_buyer_alter_item_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
    ]
